# Generated by Django 4.0.1 on 2022-01-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('date', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('response_date', models.JSONField()),
            ],
        ),
    ]
